import { useState, useEffect, useRef } from "react";

// ─── Legal content ───────────────────────────────────────────────────────────
const LEGAL_CONTENT = {
  disclosure: {
    title: "Affiliate Disclosure",
    body: `As an Amazon Associate this site earns from qualifying purchases.

Goodie Bag Generator is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com.

When you click on a product link on this site and make a purchase, we may earn a small commission at no additional cost to you. This helps support our work and keeps the tool free to use.

We only recommend products we believe will be useful or enjoyable for kids' party goodie bags. Product suggestions are AI-generated and we do not personally inspect or endorse individual sellers. Always verify product details, age-appropriateness, allergen information, and current pricing on Amazon before making a purchase.

We are not paid by Amazon or any other retailer to feature specific products. The AI generates suggestions based on your inputs, not based on sponsorship deals.`,
  },
  privacy: {
    title: "Privacy Policy",
    body: `Last updated: ${new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })}

WHAT WE COLLECT
We do not require accounts, logins, or personal information to use Goodie Bag Generator. The form inputs you provide (age range, occasion, budget, etc.) are sent to our AI provider to generate suggestions and are not stored permanently or linked to your identity.

COOKIES
We use a single browser storage item to remember whether you've accepted our cookie notice. We do not use tracking cookies, advertising cookies, or cross-site trackers on this site directly.

THIRD-PARTY SERVICES
This site uses the following third-party services:
- Anthropic (Claude AI) — processes your form inputs to generate goodie bag suggestions. See Anthropic's privacy policy at anthropic.com/privacy.
- Amazon — affiliate links lead to Amazon.com, which may use its own cookies and tracking when you visit. See Amazon's privacy policy at amazon.com/privacy.

When you click an affiliate link, Amazon may set its own cookies to track the referral. This is how we earn commissions and is standard for affiliate links across the web.

DATA WE DO NOT COLLECT
We do not collect: your name, email address, IP address (beyond standard server logs), location, or any personally identifiable information.

CHILDREN'S PRIVACY
This site is intended for use by parents and teachers planning kids' parties — not by children directly. We do not knowingly collect information from anyone under 13.

CHANGES
We may update this policy. The "Last updated" date at the top will reflect any changes.

CONTACT
For privacy questions, email support@goodiebaggenerator.com.`,
  },
  terms: {
    title: "Terms of Service",
    body: `Last updated: ${new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" })}

USE OF THE SERVICE
Goodie Bag Generator is provided free of charge as a planning tool for parents and teachers. By using this site, you agree to these terms.

AI-GENERATED CONTENT
All product suggestions, descriptions, tips, and activity ideas are generated by AI and are provided for informational and inspirational purposes only. We make no guarantees about:
- Product availability, accuracy of pricing, or current Amazon listings
- The age-appropriateness or safety of suggested items for your specific group of children
- The accuracy of allergen information for any food items suggested
- That suggested items will be in stock or meet your expectations

YOU ARE RESPONSIBLE FOR VERIFYING SUGGESTIONS
Before purchasing any item, you must independently verify:
- Current pricing and availability on Amazon
- Age-appropriateness and safety for the specific children who will receive the bags
- Allergen information against the specific dietary needs of those children
- That the item meets any applicable school or organization policies

ALLERGY DISCLAIMER
The dietary filters (Nut-Free, Dairy-Free, Gluten-Free, Vegan, School-Safe) are intended as helpful guidance only. Food allergen labeling changes over time and varies by manufacturer batch. ALWAYS read the actual product packaging and consult with caregivers about specific allergies before serving any food item to children. We are not liable for allergic reactions or any health consequences arising from suggestions on this site.

AFFILIATE LINKS
This site contains Amazon affiliate links. We may earn a commission when you make a purchase through these links. See our Affiliate Disclosure for full details.

LIMITATION OF LIABILITY
This service is provided "as is" without warranties of any kind. We are not liable for any damages, losses, or harms arising from your use of the suggestions provided. Your use of the suggestions, and the safety of any party or event you plan, is entirely your responsibility.

INTELLECTUAL PROPERTY
You may use the suggestions for personal, non-commercial party planning. You may not scrape, redistribute, or resell the AI-generated content as a competing service.

CHANGES
We may update these terms. Continued use of the site after changes constitutes acceptance.`,
  },
};

// ─── AFFILIATE TAG (replace with your real Amazon Associates tag) ─────────────
const AMAZON_TAG = "smawormom06-20";
const amazonLink = (q) =>
  `https://www.amazon.com/s?k=${encodeURIComponent(q)}&tag=${AMAZON_TAG}`;

// Fire-and-forget GA4 event. Optional-chained so an ad blocker (no gtag) can't throw.
// Send only booleans/counts/labels — never the email address or comment text.
const track = (event, params = {}) => { try { window.gtag?.("event", event, params); } catch {} };

// ─── Price range helpers ─────────────────────────────────────────────────────
// Items may have either {unitCostLow, unitCostHigh} (preferred) or {unitCost} (legacy).
// These helpers normalize both shapes so the rest of the code doesn't care.
const itemLow  = (it) => Number(it.unitCostLow  ?? it.unitCost ?? 0);
const itemHigh = (it) => Number(it.unitCostHigh ?? it.unitCost ?? 0);
const itemMid  = (it) => (itemLow(it) + itemHigh(it)) / 2;
const itemMidCost = (it) => itemMid(it) * Number(it.quantity || 1);

// Display string like "$0.40–0.65" or "$0.50" if low === high
const itemPriceLabel = (it) => {
  const lo = itemLow(it), hi = itemHigh(it);
  if (lo === hi) return `~$${lo.toFixed(2)}`;
  return `$${lo.toFixed(2)}–${hi.toFixed(2)}`;
};

// Bag total range: sum of (low × qty) to sum of (high × qty)
const bagTotalRange = (items = []) => {
  const low  = items.reduce((s, it) => s + itemLow(it)  * Number(it.quantity || 1), 0);
  const high = items.reduce((s, it) => s + itemHigh(it) * Number(it.quantity || 1), 0);
  return { low, high, mid: (low + high) / 2 };
};

// ─── Form options ─────────────────────────────────────────────────────────────
const OCCASIONS = [
  { value:"birthday",       label:"🎂 Birthday Party"     },
  { value:"halloween",      label:"🎃 Halloween"           },
  { value:"christmas",      label:"🎄 Christmas/Winter"    },
  { value:"valentines",     label:"❤️ Valentine's Day"     },
  { value:"easter",         label:"🐣 Easter"              },
  { value:"fourth_july",    label:"🇺🇸 4th of July"        },
  { value:"end_of_year",    label:"🏫 End of School Year"  },
  { value:"back_to_school", label:"🎒 Back to School"      },
  { value:"general",        label:"🎉 General Celebration" },
];

const BAG_STYLES = [
  { value:"theme",     label:"🎨 Themed",           hint:"Matches the occasion"                 },
  { value:"plastic",   label:"🛍️ Clear Plastic",    hint:"Cellophane, contents visible"        },
  { value:"paper",     label:"📜 Paper",            hint:"Kraft or printed paper bags"          },
  { value:"color_mix", label:"🌈 Color Mix",        hint:"Assorted colors variety pack"         },
  { value:"cheapest",  label:"💸 Cheapest",         hint:"Lowest cost, any style"               },
];

const ALLERGY_OPTIONS = [
  { value:"nut_free",        label:"🥜 Nut-Free"      },
  { value:"dairy_free",      label:"🥛 Dairy-Free"    },
  { value:"gluten_free",     label:"🌾 Gluten-Free"   },
  { value:"vegan",           label:"🌱 Vegan"         },
  { value:"school_safe",     label:"🏫 School-Safe"   },
];

// ─── Item category metadata ──────────────────────────────────────────────────
const CAT_META = {
  bag:          { color:"#7B2D8B", label:"The Bag"      },
  toy:          { color:"#FF6B6B", label:"Toy"          },
  hero:         { color:"#FF3D77", label:"⭐ Hero"      },
  candy:        { color:"#FFD93D", label:"Candy"        },
  activity:     { color:"#6BCB77", label:"Activity"     },
  stationery:   { color:"#4D96FF", label:"Stationery"   },
  book:         { color:"#CC5DE8", label:"Book"         },
  bulk:         { color:"#F77F00", label:"Bulk Filler"  },
  seasonal:     { color:"#7B2D8B", label:"Seasonal"     },
  craft:        { color:"#CC2529", label:"Craft"        },
  other:        { color:"#FF922B", label:"Other"        },
};

// ─── Packaging add-ons (always shown with the bag) ───────────────────────────
// Tissue paper is a near-universal goodie bag essential — show it as a guaranteed add-on.
const PACKAGING_ADDONS = [
  {
    name: "Themed Tissue Paper",
    emoji: "🎀",
    searchByStyle: {
      theme:     "tissue paper",      // appended to occasion-based theme below
      plastic:   "colored tissue paper bulk pack",
      paper:     "kraft tissue paper natural",
      color_mix: "rainbow tissue paper assorted colors",
      cheapest:  "tissue paper bulk cheap",
    },
  },
  {
    name: "Curly Ribbon",
    emoji: "🎗️",
    searchByStyle: {
      theme:     "curly ribbon party",
      plastic:   "curly ribbon assorted colors",
      paper:     "twine bakers natural",
      color_mix: "curly ribbon rainbow assorted",
      cheapest:  "curly ribbon bulk",
    },
  },
];

// ─── Product keywords for auto-linking in tip text ────────────────────────────
// Order matters: longer/more specific phrases must come first so "curly ribbon"
// is matched before "ribbon".
const TIP_KEYWORDS = [
  { phrase: "curly ribbon",    query: "curly ribbon party"             },
  { phrase: "tissue paper",    query: "tissue paper bulk"              },
  { phrase: "cellophane wrap", query: "cellophane wrap rolls"          },
  { phrase: "baker's twine",   query: "bakers twine"                   },
  { phrase: "bakers twine",    query: "bakers twine"                   },
  { phrase: "gift tags",       query: "gift tags kids party"           },
  { phrase: "name tags",       query: "name tags party kids"           },
  { phrase: "twist ties",      query: "twist ties party bags"          },
  { phrase: "ribbon",          query: "ribbon party bulk"              },
  { phrase: "twine",           query: "bakers twine"                   },
  { phrase: "stickers",        query: "kids stickers bulk"             },
  { phrase: "washi tape",      query: "washi tape kids"                },
  { phrase: "permanent marker",query: "sharpie permanent markers"      },
  { phrase: "sharpies",        query: "sharpie markers"                },
];

// ─── Confetti ─────────────────────────────────────────────────────────────────
const C_SHAPES = ["●","★","♦","▲","♥"];
const C_COLORS = ["#FF6B6B","#FFD93D","#6BCB77","#4D96FF","#FF922B","#CC5DE8","#F06595"];

// ─── LinkedTipText: scans tip text and turns product keywords into Amazon links ──
function LinkedTipText({ text }) {
  if (!text) return null;

  // Build a regex from all phrases, longest-first to prevent shorter matches eating longer ones
  const sorted = [...TIP_KEYWORDS].sort((a, b) => b.phrase.length - a.phrase.length);
  const pattern = new RegExp(
    `(${sorted.map(k => k.phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})`,
    "gi"
  );

  const parts = text.split(pattern);
  const linkedPhrases = new Set(); // de-dupe: only first occurrence becomes a link

  return (
    <>
      {parts.map((part, i) => {
        const matchedKw = sorted.find(k => k.phrase.toLowerCase() === part.toLowerCase());
        if (matchedKw && !linkedPhrases.has(matchedKw.phrase.toLowerCase())) {
          linkedPhrases.add(matchedKw.phrase.toLowerCase());
          return (
            <a key={i}
              href={amazonLink(matchedKw.query)}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                color: "#FF9900",
                fontWeight: 800,
                textDecoration: "underline",
                textDecorationStyle: "dotted",
                textUnderlineOffset: "3px",
              }}>
              {part}
            </a>
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

function Confetti({ trigger }) {
  const [pieces, setPieces] = useState([]);
  useEffect(() => {
    if (!trigger) return;
    setPieces(Array.from({ length: 52 }, (_, i) => ({
      id:i, left:Math.random()*100,
      color:C_COLORS[i%C_COLORS.length],
      shape:C_SHAPES[i%C_SHAPES.length],
      delay:Math.random()*1.4, size:10+Math.random()*14,
    })));
    const t = setTimeout(() => setPieces([]), 4500);
    return () => clearTimeout(t);
  }, [trigger]);
  return (
    <div style={{position:"fixed",inset:0,pointerEvents:"none",zIndex:9999,overflow:"hidden"}}>
      {pieces.map(p=>(
        <span key={p.id} style={{position:"absolute",left:`${p.left}%`,top:"-20px",
          color:p.color,fontSize:p.size,
          animation:`cfFall 3.8s ${p.delay}s ease-in forwards`}}>{p.shape}</span>
      ))}
      <style>{`@keyframes cfFall{0%{transform:translateY(0) rotate(0);opacity:1}80%{opacity:1}100%{transform:translateY(110vh) rotate(720deg);opacity:0}}`}</style>
    </div>
  );
}

// ─── Validation (lightweight client-side guardrails) ──────────────────────────
const BANNED_KEYWORDS = ["gum","chewing gum","latex","peanut"];

function validateBag(bag, form) {
  const errors = [];
  const budget = parseFloat(form.budget);

  if (!bag.items || bag.items.length < 4) errors.push("Too few items");

  // Use midpoint sum for budget check (the displayed "expected" total)
  const { mid } = bagTotalRange(bag.items || []);
  if (mid > budget * 1.05) errors.push("Over budget");

  // Banned keyword scan
  for (const item of bag.items || []) {
    const txt = `${item.name} ${item.description}`.toLowerCase();
    for (const kw of BANNED_KEYWORDS) {
      // Skip nut-related blocks if school-safe/nut-free is not selected
      if (kw === "peanut" && !form.allergies.includes("nut_free") && !form.allergies.includes("school_safe")) continue;
      if (txt.includes(kw)) errors.push(`Banned keyword "${kw}" in ${item.name}`);
    }
  }

  // Hero item check (must have at least one)
  const hasHero = (bag.items || []).some(i => i.category === "hero");
  if (!hasHero) errors.push("Missing hero item");

  // Bag-as-item check (must be first item)
  const firstIsBag = bag.items?.[0]?.category === "bag";
  if (!firstIsBag) errors.push("Bag not included as first item");

  return errors;
}

// ─── Generation cache ─────────────────────────────────────────────────────────
// Identical input combos return cached results instead of re-calling the API.
// Module-level so cache persists across re-renders within a single session.
const GENERATION_CACHE = new Map();
const CACHE_MAX_SIZE = 100;

function cacheKey(form) {
  return JSON.stringify({
    a: `${form.ageMin}-${form.ageMax}`,
    o: form.occasion,
    b: form.bagStyle,
    c: form.count,
    bg: form.budget,
    f: form.includeFood,
    al: [...form.allergies].sort().join(","),
  });
}

function cacheGet(form) {
  const k = cacheKey(form);
  const hit = GENERATION_CACHE.get(k);
  if (!hit) return null;
  // Refresh recency by re-inserting (LRU-ish)
  GENERATION_CACHE.delete(k);
  GENERATION_CACHE.set(k, hit);
  return hit;
}

function cacheSet(form, bag) {
  const k = cacheKey(form);
  GENERATION_CACHE.set(k, bag);
  // Evict oldest entries if we exceed max size
  while (GENERATION_CACHE.size > CACHE_MAX_SIZE) {
    const firstKey = GENERATION_CACHE.keys().next().value;
    GENERATION_CACHE.delete(firstKey);
  }
}

// ─── Popular-themes quick-pick grid ──────────────────────────────────────────
// Wrapping grid of prebuilt themed bags (reuses .occ-grid / .occ-btn, matching
// the Occasion buttons). Tapping a chip calls loadPreset(key) — instant load of
// the already-warmed bag (no /api/generate, no enrichBag stagger). Chips wrap to
// multiple rows (no scroll, no arrows); height is constant per viewport, which
// keeps the WordPress iframe embed stable. Label and live preset key are
// decoupled: only the display label changed for Spider-Man; the `spidey`
// key/URL-param is unchanged.
const PRESET_THEMES = [
  { key: "bluey",       label: "Bluey",       emoji: "🐶" },
  { key: "paw-patrol",  label: "Paw Patrol",  emoji: "🐾" },
  { key: "spidey",      label: "Spider-Man",  emoji: "🕷️" },
  { key: "minecraft",   label: "Minecraft",   emoji: "⛏️" },
  { key: "pokemon",     label: "Pokémon",     emoji: "⚡" },
  { key: "super-mario", label: "Super Mario", emoji: "🍄" },
  { key: "disney-princess", label: "Disney Princess", emoji: "👑" },
  { key: "mickey-mouse",    label: "Mickey Mouse",   emoji: "🐭" },
];

function PopularThemes({ onPick, disabled }) {
  return (
    <div style={{ marginBottom: "1.6rem" }}>
      <label className="flabel">🔥 Popular themes</label>
      <div
        className="occ-grid"
        role="group"
        aria-label="Popular party themes — tap one for an instant pre-built bag"
      >
        {PRESET_THEMES.map((t) => (
          <button
            key={t.key}
            type="button"
            className="occ-btn"
            disabled={disabled}
            onClick={() => onPick(t.key)}
            style={{ cursor: disabled ? "wait" : "pointer" }}
          >
            <span aria-hidden="true" style={{ marginRight: 6 }}>{t.emoji}</span>{t.label}
          </button>
        ))}
      </div>
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function GoodyBagGenerator() {
  const [form, setForm] = useState({
    ageMin:"4", ageMax:"8",
    occasion:"birthday",
    bagStyle:"theme",
    count:"20",
    budget:"5",
    includeFood:true,
    allergies:[],
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [confetti, setConfetti] = useState(0);
  const [debugInfo, setDebugInfo] = useState(null);
  const [enrichingKeys, setEnrichingKeys] = useState(() => new Set()); // item indices still resolving
  const [bagId, setBagId] = useState(null);              // stable id for the current bag (for the return link)
  const [email, setEmail] = useState("");
  const [emailStatus, setEmailStatus] = useState(null);  // null | "sending" | "sent" | "error"
  const [rating, setRating] = useState(0);               // 0 = none chosen yet
  const [ratingComment, setRatingComment] = useState("");
  const [ratingStatus, setRatingStatus] = useState(null); // null | "sending" | "sent"
  const [modalContent, setModalContent] = useState(null); // "privacy" | "terms" | "disclosure" | null
  const [cookieConsent, setCookieConsent] = useState(() => {
    // Check if user previously accepted (using a simple in-memory flag fallback)
    try { return typeof localStorage !== "undefined" && localStorage.getItem("gbg_cookie_consent") === "accepted"; }
    catch { return false; }
  });
  const resultsRef = useRef(null);
  const bagSourceRef = useRef(null);   // last bag_rendered source — attached to downstream events

  const acceptCookies = () => {
    setCookieConsent(true);
    try { localStorage.setItem("gbg_cookie_consent", "accepted"); } catch {}
  };

  const handleChange = e => setForm(f => ({ ...f, [e.target.name]: e.target.value }));
  const toggleAllergy = v => setForm(f => ({
    ...f,
    allergies: f.allergies.includes(v) ? f.allergies.filter(a=>a!==v) : [...f.allergies, v],
  }));

  const buildPrompt = () => {
    const occLabel  = OCCASIONS.find(o=>o.value===form.occasion)?.label || form.occasion;
    const bagLabel  = BAG_STYLES.find(b=>b.value===form.bagStyle)?.label || form.bagStyle;
    const bagHint   = BAG_STYLES.find(b=>b.value===form.bagStyle)?.hint  || "";
    const allergies = form.allergies.length
      ? form.allergies.map(a => ALLERGY_OPTIONS.find(o=>o.value===a)?.label).join(", ")
      : "None";

    return `You are an expert at curating kids' party goodie bags. Generate a complete, age-appropriate bag plan based on these inputs.

INPUTS:
- Age range: ${form.ageMin}-${form.ageMax} years old
- Occasion: ${occLabel}
- Bag style: ${bagLabel} (${bagHint})
- Number of bags: ${form.count}
- Budget per bag: $${form.budget}
- Include food/candy: ${form.includeFood ? "YES" : "NO — exclude all consumables"}
- Dietary filters: ${allergies}

RULES:

1. BAG AS ITEM: The first item in the items array MUST be the bag itself (category: "bag"). Match the bagStyle preference:
   - plastic: clear cellophane/cello bags
   - paper: kraft or themed printed paper bags
   - theme: bags themed to the occasion (e.g., Halloween-printed for Halloween)
   - color_mix: assorted color variety packs
   - cheapest: whatever has the lowest unit cost

2. HERO ITEM: At least ONE item (not the bag) MUST have category "hero" — a proven crowd-pleaser that anchors the bag.

   UNIVERSAL HEROES (work for ANY occasion, themed to match the occasion when possible):
   - Non-food: themed pencils, themed stickers, themed kid sunglasses
   - Candy (skip ALL of these if includeFood is NO or if they violate any active allergy filter):
     - Ring Pops (peanut-free, gluten-free, dairy-free — generally allergy-friendly)
     - Smarties (peanut-free, gluten-free, dairy-free, vegan — extremely allergy-friendly)
     - Pez (check current allergen labeling; generally peanut-free and gluten-free)
     - Candy bracelets (typically peanut-free and gluten-free; verify for school-safe)

   OCCASION-SPECIFIC HEROES (preferred when applicable):
   - Birthday: glow sticks, mini Play-Doh, temporary tattoos, bouncy balls
   - Halloween: glow sticks, slap bracelets, light-up rings, mini pumpkin erasers, glow-in-the-dark items
   - Valentine's: heart-shaped sunglasses, conversation hearts, heart-themed slap bracelets
   - Easter: bunny stickers, mini chocolate eggs, plastic eggs with stickers inside
   - 4th of July: light-up bracelets, American flag sunglasses, glow sticks (red/white/blue), patriotic slap bracelets
   - Christmas: mini stockings, jingle bell bracelets, holiday slap bracelets, candy canes
   - End of School Year: SUMMER-THEMED — mini water guns, sidewalk chalk, bubble wands, sunglasses, beach balls, flip-flop keychains, popsicle-shaped erasers
   - Back to School: FUNCTIONAL BUT EXCITING — fun shaped pencils, scented markers, mood-changing erasers, novelty pencil sharpeners, eraser caps shaped like animals, cool kid sunglasses
   - General Celebration: pick from universal heroes

   IMPORTANT: When picking a candy hero, verify it doesn't violate any active allergy filter. School-Safe excludes the top 9 allergens, so most universal candy heroes still qualify but always double-check the specific product line.

3. QUALITY FLOOR:
   - Never recommend items where unitCostLow is below $0.40 UNLESS they're bulk fillers (stickers, mini erasers)
   - Every item must be specific and identifiable on Amazon — use real product names like "Ring Pops Variety Pack 24 Count" not generic "lollipops"
   - searchQuery should match how parents actually search Amazon (e.g., "kids sunglasses bulk pack neon")

4. SAFETY (AGE-CALIBRATED):
   - Ages 1-3: NO items under 1.75 inches, NO small parts, NO latex balloons, NO hard candy, NO small magnets
   - Ages 4-6: avoid sharp edges, small magnets, items needing close supervision
   - All ages: NO batteries unless included, NO complex assembly, NO gum (banned in most classrooms)

5. ALLERGY HANDLING (be conservative — when in doubt, exclude):
   - Nut-Free: no peanut, tree nut, or "may contain nuts" items
   - Dairy-Free: no milk chocolate, no cream candies
   - Gluten-Free: no wheat-based candies, no pretzels, no gluten cookies
   - Vegan: no dairy, no gelatin (excludes most gummies)
   - School-Safe: exclude top 9 allergens (milk, eggs, fish, shellfish, tree nuts, peanuts, wheat, soy, sesame)
   - If includeFood is NO: zero consumables in the bag

6. ANTI-PATTERNS:
   - No religious content
   - No scary content for kids under 6
   - No gum, ever
   - No gender-specific items unless user explicitly requests
   - No items requiring batteries unless included

7. BUDGET: totalPerBag MUST be <= $${form.budget}. Include the bag cost in this total.

8. ITEM COUNT: Include exactly 5-7 items TOTAL (including the bag as item 1).

9. PACKAGING TIP: Write the packagingTip to mention at least one specific packaging product naturally (tissue paper, curly ribbon, baker's twine, gift tags, washi tape, etc.) — these get auto-linked for shopping. Make it actionable, not generic. Good: "Stuff each bag with two sheets of tissue paper in coordinating colors, then tie with curly ribbon for a polished look." Bad: "Make them look nice."

10. PRICE RANGES: Every item must include unitCostLow and unitCostHigh — these are estimated per-unit prices on Amazon. The range should reflect realistic variation across sellers and pack sizes (e.g., 0.60 to 0.90 for a Ring Pop). For totalPerBag, use the MIDPOINT: sum of ((unitCostLow + unitCostHigh) / 2 × quantity) across all items. Keep ranges tight (within 30-50% spread) — wider ranges look uncertain.

EXAMPLE OUTPUT (for ages 5-7, Birthday, Theme bag, $5 budget, food=yes, no allergies):
{
  "theme": "Superhero Squad",
  "tagline": "Pow! A bag of mini-thrills for tiny heroes",
  "totalPerBag": 4.85,
  "items": [
    {"name":"Superhero Themed Party Favor Bags 24 Pack","emoji":"🦸","description":"Bright themed bags that make kids feel like they're getting something special","unitCostLow":0.40,"unitCostHigh":0.65,"quantity":1,"searchQuery":"superhero party favor bags bulk","category":"bag"},
    {"name":"Ring Pops Variety Pack","emoji":"💍","description":"The legendary candy ring that every kid asks for","unitCostLow":0.60,"unitCostHigh":0.90,"quantity":1,"searchQuery":"ring pops variety pack","category":"hero"},
    {"name":"Mini Play-Doh 4-Pack","emoji":"🎨","description":"Sparks open-ended creativity long after the party ends","unitCostLow":0.85,"unitCostHigh":1.20,"quantity":1,"searchQuery":"play doh mini party pack","category":"activity"},
    {"name":"Superhero Temporary Tattoos","emoji":"💪","description":"Kids love wearing these home as 'proof' they attended","unitCostLow":0.15,"unitCostHigh":0.30,"quantity":2,"searchQuery":"superhero temporary tattoos kids","category":"toy"},
    {"name":"Bouncy Ball Assortment","emoji":"⚽","description":"Classic party favor that delivers instant entertainment","unitCostLow":0.25,"unitCostHigh":0.40,"quantity":2,"searchQuery":"bouncy balls bulk assorted","category":"toy"},
    {"name":"Cartoon Sticker Sheets","emoji":"⭐","description":"Cheap, beloved by every kid, perfect bag filler","unitCostLow":0.10,"unitCostHigh":0.20,"quantity":3,"searchQuery":"kids sticker sheets bulk","category":"bulk"}
  ],
  "packagingTip":"Stuff each bag with a sheet of coordinating tissue paper, then tie with curly ribbon for a polished look.",
  "teacherTip":"Pre-assemble bags the night before and store in a cool spot — chocolate items can melt in classrooms by afternoon.",
  "funActivity":"Set up a 'superhero training course' with masking-tape laser beams kids can crawl under."
}

Now generate a bag for the user's actual inputs. Return ONLY valid JSON, no markdown fences, no explanation.`;
  };

  const generateOnce = async () => {
    const res = await fetch("/api/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "claude-sonnet-4-6",
        max_tokens: 1500,
        messages: [{ role:"user", content: buildPrompt() }],
      }),
    });
    const raw = await res.text();
    if (!res.ok) throw new Error(`API ${res.status}: ${raw.slice(0,200)}`);
    const data = JSON.parse(raw);
    if (data.error) throw new Error(`[${data.error.type}] ${data.error.message}`);
    const text = (data.content||[]).map(b=>b.text||"").join("");
    const match = text.match(/\{[\s\S]*\}/);
    return JSON.parse(match ? match[0] : text);
  };

  // Enrich ONE item via the server; returns the enriched item (or the original on miss/failure).
  const enrichOneItem = async (item) => {
    try {
      const r = await fetch("/api/enrich", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ item }),
      });
      if (!r.ok) return item;
      const data = await r.json();
      return data.item || item;
    } catch { return item; }
  };

  // Progressive enhancement, STAGGERED: the bag renders instantly with search links,
  // then items resolve ONE BY ONE (~1.1s apart to respect the 1 req/sec API limit).
  // Cached items return fast; new ones trickle in. Each card updates as it resolves.
  const enrichBag = async (bag) => {
    const items = bag.items || [];
    // Match each item to its result index by identity of name+searchQuery (stable within a render).
    setEnrichingKeys(new Set(items.map((_, i) => i)));
    for (let i = 0; i < items.length; i++) {
      const enriched = await enrichOneItem(items[i]);
      // Patch just this index into the current result; guard against a newer bag having replaced it.
      setResult(prev => {
        if (!prev || !prev.items || prev.items[i]?.name !== items[i].name) return prev;
        const next = prev.items.slice();
        next[i] = enriched;
        return { ...prev, items: next };
      });
      setEnrichingKeys(prev => { const n = new Set(prev); n.delete(i); return n; });
      if (i < items.length - 1) await new Promise(r => setTimeout(r, 1100)); // stagger
    }
  };

  // Email-my-results: stores the bag server-side + adds the Kit subscriber → triggers the email.
  const submitEmail = async () => {
    if (!email || !/.+@.+\..+/.test(email)) { setEmailStatus("error"); return; }
    if (!result || !bagId) return;
    setEmailStatus("sending");
    try {
      const r = await fetch("/api/subscribe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, bagId, bag: result }),
      });
      if (r.ok) track("email_signup", { bag_source: bagSourceRef.current });
      setEmailStatus(r.ok ? "sent" : "error");
    } catch { setEmailStatus("error"); }
  };

  // Rating: stars + optional comment → /api/feedback (stored in Upstash).
  // Star tap records the rating silently (so it's never lost) but keeps the
  // comment box open. Only an explicit "Send feedback" shows the thank-you.
  const recordRating = async (stars, comment = "") => {
    try {
      await fetch("/api/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          bagId, rating: stars, comment,
          occasion: form.occasion, ageMin: form.ageMin, ageMax: form.ageMax, budget: form.budget,
        }),
      });
    } catch { /* fail quietly — don't nag over a rating */ }
  };

  const pickStar = (n) => {
    track("rating_submitted", { stars: n, has_comment: !!ratingComment });
    setRating(n); recordRating(n, "");
  };       // silent capture
  const sendComment = async () => { await recordRating(rating, ratingComment); setRatingStatus("sent"); };

  // Deep-link rehydration: ?bag=<id> loads a saved bag; ?preset=<key> loads a prebuilt themed bag.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const bagId = params.get("bag");
    const presetKey = params.get("preset");
    if (!bagId && !presetKey) return;
    (async () => {
      setLoading(true);
      try {
        const url = bagId
          ? `/api/bag?id=${encodeURIComponent(bagId)}`
          : `/api/preset?key=${encodeURIComponent(presetKey)}`;
        const r = await fetch(url);
        if (r.ok) {
          const { bag } = await r.json();
          setResult(bag);
          bagSourceRef.current = "return_link";
          track("bag_rendered", { source: "return_link", item_count: bag.items?.length });
          setBagId(bagId || crypto.randomUUID());
          setTimeout(() => resultsRef.current?.scrollIntoView({ behavior:"smooth" }), 200);
        }
      } catch { /* ignore — user can just generate fresh */ }
      finally { setLoading(false); }
    })();
  }, []);

  const generate = async (bypassCache = false) => {
    track("generate_clicked", {
      occasion: form.occasion,
      age_range: `${form.ageMin}-${form.ageMax}`,
      budget: form.budget,
      bag_style: form.bagStyle,
      include_food: form.includeFood,
      allergy_count: form.allergies.length,
    });
    setLoading(true); setError(null); setResult(null); setDebugInfo(null);
    try {
      // Cache hit shortcut: same inputs return cached result instantly, no API call
      if (!bypassCache) {
        const cached = cacheGet(form);
        if (cached) {
          setResult(cached);
          bagSourceRef.current = "cache";
          track("bag_rendered", { source: "cache", item_count: cached.items?.length, attempts: 0 });
          setBagId(crypto.randomUUID());
          setEmailStatus(null); setEmail("");
          setRating(0); setRatingComment(""); setRatingStatus(null);
          enrichBag(cached);
          setDebugInfo({ attempts: 0, cached: true });
          setConfetti(c => c + 1);
          setTimeout(() => resultsRef.current?.scrollIntoView({ behavior:"smooth" }), 200);
          setLoading(false);
          return;
        }
      }

      // Try up to 2 times if validation fails
      let bag, errors, attempts = 0;
      for (attempts = 1; attempts <= 2; attempts++) {
        bag = await generateOnce();
        errors = validateBag(bag, form);
        if (errors.length === 0) break;
      }
      cacheSet(form, bag);
      setResult(bag);
      bagSourceRef.current = "generate";
      track("bag_rendered", { source: "generate", item_count: bag.items?.length, attempts });
      setBagId(crypto.randomUUID());
      setEmailStatus(null); setEmail("");
      setRating(0); setRatingComment(""); setRatingStatus(null);
      enrichBag(bag);
      setDebugInfo({ attempts, validationErrors: errors, cached: false });
      setConfetti(c => c + 1);
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior:"smooth" }), 200);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  // Quick-pick: load a prebuilt, fully-enriched themed bag straight from /api/preset.
  // No enrichBag / no /api/generate — the preset is already enriched, which is the speed win.
  const loadPreset = async (presetKey) => {
    track("preset_used", { preset_key: presetKey });
    setLoading(true); setError(null); setResult(null); setDebugInfo(null);
    try {
      const r = await fetch(`/api/preset?key=${encodeURIComponent(presetKey)}`);
      if (!r.ok) {
        // Graceful fallback: if the preset hasn't been warmed yet (cron not run,
        // or first days of bootstrap), tell the user and let them generate normally.
        if (r.status === 404) {
          setError("This themed bag isn't ready yet — try generating one with the form below.");
        } else {
          setError("Couldn't load that themed bag right now.");
        }
        return;
      }
      const { bag } = await r.json();
      setResult(bag);
      bagSourceRef.current = "preset";
      track("bag_rendered", { source: "preset", item_count: bag.items?.length });
      setBagId(crypto.randomUUID());
      setEmailStatus(null); setEmail("");
      setRating(0); setRatingComment(""); setRatingStatus(null);
      setConfetti(c => c + 1);
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior:"smooth" }), 200);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  // Regenerate button bypasses the cache so users always get a fresh idea
  const regenerate = () => generate(true);

  // ─── Replace a single item ──────────────────────────────────────────────────
  const [swappingIndex, setSwappingIndex] = useState(null);
  const [justSwappedIndex, setJustSwappedIndex] = useState(null);

  const replaceItem = async (itemIndex) => {
    if (!result || swappingIndex !== null) return;
    setSwappingIndex(itemIndex);
    setError(null);

    try {
      const rejectedItem = result.items[itemIndex];
      const otherItems   = result.items.filter((_, i) => i !== itemIndex);
      const otherCost    = otherItems.reduce((sum, it) => sum + itemMidCost(it), 0);
      const remaining    = parseFloat(form.budget) - otherCost;

      const occLabel  = OCCASIONS.find(o=>o.value===form.occasion)?.label || form.occasion;
      const bagLabel  = BAG_STYLES.find(b=>b.value===form.bagStyle)?.label || form.bagStyle;
      const allergies = form.allergies.length
        ? form.allergies.map(a => ALLERGY_OPTIONS.find(o=>o.value===a)?.label).join(", ")
        : "None";

      const swapPrompt = `You are replacing ONE item in an existing kids' goodie bag.

BAG CONTEXT:
- Age range: ${form.ageMin}-${form.ageMax}
- Occasion: ${occLabel}
- Bag style: ${bagLabel}
- Include food: ${form.includeFood ? "YES" : "NO"}
- Dietary filters: ${allergies}

REJECTED ITEM (do NOT suggest this or anything too similar):
${JSON.stringify(rejectedItem)}

OTHER ITEMS ALREADY IN THE BAG (do NOT duplicate these):
${JSON.stringify(otherItems.map(i => ({ name: i.name, category: i.category })))}

CONSTRAINTS:
- Suggest ONE replacement item in category "${rejectedItem.category}"
- Midpoint cost (((unitCostLow + unitCostHigh) / 2) × quantity) must be <= $${remaining.toFixed(2)}
- Must be different from the rejected item AND from all other items in the bag
- Follow all the same safety, allergy, and quality rules as a normal bag generation
- If category is "bag": match the bag style "${bagLabel}"
- If category is "hero": must still be a proven crowd-pleaser
- Item must be specific and identifiable on Amazon (real product name, not generic)
- Never recommend items where unitCostLow is below $0.40 UNLESS the category is "bulk"
- Provide BOTH unitCostLow and unitCostHigh (realistic Amazon price range, 30-50% spread)

Return ONLY a single JSON object for the replacement item, no markdown fences, no explanation:
{
  "name": "...",
  "emoji": "...",
  "description": "...",
  "unitCostLow": 0.00,
  "unitCostHigh": 0.00,
  "quantity": 1,
  "searchQuery": "...",
  "category": "${rejectedItem.category}"
}`;

      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-6",
          max_tokens: 400,
          messages: [{ role:"user", content: swapPrompt }],
        }),
      });
      const raw = await res.text();
      if (!res.ok) throw new Error(`API ${res.status}: ${raw.slice(0,200)}`);
      const data = JSON.parse(raw);
      if (data.error) throw new Error(`[${data.error.type}] ${data.error.message}`);
      const text = (data.content||[]).map(b=>b.text||"").join("");
      const match = text.match(/\{[\s\S]*\}/);
      const newItem = JSON.parse(match ? match[0] : text);

      // Build the new bag with the replaced item; total is computed live from helpers
      const newItems = result.items.map((it, i) => i === itemIndex ? newItem : it);
      const { mid: newTotal } = bagTotalRange(newItems);

      setResult({ ...result, items: newItems, totalPerBag: newTotal });
      setJustSwappedIndex(itemIndex);
      setTimeout(() => setJustSwappedIndex(null), 600);

      // Enrich the swapped-in item too (was previously left as a search-link-only item).
      setEnrichingKeys(prev => { const n = new Set(prev); n.add(itemIndex); return n; });
      const enrichedNew = await enrichOneItem(newItem);
      setResult(prev => {
        if (!prev || !prev.items || prev.items[itemIndex]?.name !== newItem.name) return prev;
        const next = prev.items.slice();
        next[itemIndex] = enrichedNew;
        return { ...prev, items: next, totalPerBag: bagTotalRange(next).mid };
      });
      setEnrichingKeys(prev => { const n = new Set(prev); n.delete(itemIndex); return n; });
    } catch (e) {
      setError(`Swap failed: ${e.message}`);
    } finally {
      setSwappingIndex(null);
    }
  };

  const totalEst = (parseFloat(form.budget||0) * parseInt(form.count||0)).toFixed(2);

  return (
    <div style={{minHeight:"100vh",background:"#FFF8F0",fontFamily:"'Nunito',sans-serif"}}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fredoka+One&family=Nunito:wght@400;600;700;800&display=swap');
        *{box-sizing:border-box;margin:0;padding:0}
        .hero-title{font-family:'Fredoka One',cursive;font-size:clamp(2.2rem,6vw,3.8rem);line-height:1.1;background:linear-gradient(135deg,#FF6B6B 0%,#FF922B 35%,#FFD93D 65%,#6BCB77 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}
        .card{background:#fff;border-radius:24px;box-shadow:0 4px 24px rgba(0,0,0,0.07);padding:2rem}
        .flabel{font-family:'Fredoka One',cursive;font-size:1rem;color:#444;margin-bottom:6px;display:block}
        .finput{width:100%;padding:12px 16px;border:2.5px solid #F0E6FF;border-radius:14px;font-family:'Nunito',sans-serif;font-size:1rem;font-weight:700;color:#333;background:#FAFAFA;outline:none;transition:border-color .2s,box-shadow .2s;appearance:none;-webkit-appearance:none}
        .finput:focus{border-color:#CC5DE8;box-shadow:0 0 0 3px rgba(204,93,232,0.15);background:#fff}
        .occ-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(155px,1fr));gap:10px}
        .occ-btn{padding:10px 12px;border-radius:14px;border:2.5px solid #F0E6FF;background:#FAFAFA;font-family:'Nunito',sans-serif;font-weight:700;font-size:0.85rem;cursor:pointer;transition:all .15s;text-align:center;color:#555}
        .occ-btn:hover{border-color:#CC5DE8;background:#F9F0FF}
        .occ-btn.sel{border-color:#CC5DE8;background:#F3E0FF;color:#7B2FA8;box-shadow:0 2px 10px rgba(204,93,232,0.2)}
        .bag-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(135px,1fr));gap:10px}
        .bag-btn{padding:10px 12px;border-radius:14px;border:2.5px solid #F0E6FF;background:#FAFAFA;font-weight:700;font-size:0.82rem;cursor:pointer;transition:all .15s;text-align:center;color:#555}
        .bag-btn .hint{display:block;font-size:0.7rem;font-weight:600;color:#aaa;margin-top:3px}
        .bag-btn:hover{border-color:#CC5DE8;background:#F9F0FF}
        .bag-btn.sel{border-color:#CC5DE8;background:#F3E0FF;color:#7B2FA8;box-shadow:0 2px 10px rgba(204,93,232,0.2)}
        .bag-btn.sel .hint{color:#a576c4}
        .all-grid{display:flex;flex-wrap:wrap;gap:8px}
        .all-chip{padding:7px 13px;border-radius:30px;border:2px solid #F0E6FF;background:#FAFAFA;font-weight:700;font-size:0.83rem;cursor:pointer;transition:all .15s;color:#555}
        .all-chip:hover{border-color:#CC5DE8}
        .all-chip.sel{border-color:#6BCB77;background:#E8F5E9;color:#2E7D32}
        .toggle{display:inline-flex;align-items:center;gap:10px;cursor:pointer}
        .toggle-slider{position:relative;width:46px;height:26px;background:#ddd;border-radius:99px;transition:background .2s}
        .toggle-slider::after{content:"";position:absolute;top:3px;left:3px;width:20px;height:20px;background:#fff;border-radius:50%;transition:transform .2s;box-shadow:0 1px 3px rgba(0,0,0,0.2)}
        .toggle input{display:none}
        .toggle input:checked+.toggle-slider{background:#6BCB77}
        .toggle input:checked+.toggle-slider::after{transform:translateX(20px)}
        .gen-btn{width:100%;padding:18px;border:none;border-radius:20px;background:linear-gradient(135deg,#FF6B6B,#FF922B);color:#fff;font-family:'Fredoka One',cursive;font-size:1.3rem;cursor:pointer;transition:transform .15s,box-shadow .15s;box-shadow:0 6px 20px rgba(255,107,107,0.4);letter-spacing:.3px}
        .gen-btn:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 10px 28px rgba(255,107,107,0.45)}
        .gen-btn:active:not(:disabled){transform:translateY(1px)}
        .gen-btn:disabled{filter:brightness(0.8);cursor:not-allowed}
        .icard{border-radius:18px;padding:1.1rem 1.3rem;border:2.5px solid transparent;background:#fff;box-shadow:0 2px 12px rgba(0,0,0,0.06);transition:transform .18s,box-shadow .18s}
        .icard:hover{transform:translateY(-3px);box-shadow:0 8px 24px rgba(0,0,0,0.1)}
        .icard.hero-card{background:linear-gradient(135deg,#fff 0%,#FFF0F5 100%);border-width:3px}
        .icard.bag-card{background:linear-gradient(135deg,#fff 0%,#F3E0FF 100%);border-width:3px}
        .cbadge{display:inline-block;padding:3px 10px;border-radius:30px;font-size:0.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:#fff}
        .tip-box{border-radius:16px;padding:1rem 1.2rem;font-size:.92rem;font-weight:600;display:flex;gap:10px;align-items:flex-start}
        .spin{width:20px;height:20px;border:3px solid rgba(255,255,255,0.4);border-top-color:#fff;border-radius:50%;animation:sp .7s linear infinite;display:inline-block;vertical-align:middle;margin-right:8px}
        @keyframes sp{to{transform:rotate(360deg)}}
        .err-box{background:#FFF0F0;border:2px solid #FFB3B3;border-radius:16px;padding:1rem 1.2rem;color:#C0392B;font-weight:700;margin-bottom:1.5rem;font-size:.9rem;word-break:break-word}
        .amz-btn{display:inline-flex;align-items:center;gap:5px;padding:8px 16px;border-radius:30px;background:#FF9900;color:#fff;font-weight:800;font-size:.82rem;text-decoration:none;box-shadow:0 2px 8px rgba(255,153,0,0.4);transition:transform .15s,box-shadow .15s}
        .amz-btn:hover{transform:translateY(-2px);box-shadow:0 5px 14px rgba(255,153,0,0.5)}
        .swap-btn{display:inline-flex;align-items:center;gap:5px;padding:8px 14px;border-radius:30px;background:#fff;color:#7B2FA8;border:2px solid #E1BEE7;font-weight:800;font-size:.78rem;cursor:pointer;transition:all .15s;font-family:'Nunito',sans-serif}
        .swap-btn:hover:not(:disabled){background:#F3E0FF;border-color:#CC5DE8;transform:translateY(-2px)}
        .swap-btn:disabled{opacity:.5;cursor:not-allowed}
        .swap-spin{width:13px;height:13px;border:2px solid rgba(123,47,168,0.3);border-top-color:#7B2FA8;border-radius:50%;animation:sp .7s linear infinite;display:inline-block}
        .item-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px;align-items:center}
        .finding-product{font-size:.6rem;font-weight:800;color:#CC5DE8;margin-top:4px;line-height:1.2;animation:fpPulse 1.2s ease-in-out infinite}
        @keyframes fpPulse{0%,100%{opacity:.45}50%{opacity:1}}
        .more-btn{display:inline-flex;align-items:center;gap:5px;padding:8px 14px;border-radius:30px;background:#fff;color:#999;border:2px solid #E5E5E5;font-weight:800;font-size:.78rem;cursor:pointer;text-decoration:none;transition:all .15s;font-family:'Nunito',sans-serif}
        .more-btn:hover{background:#FAFAFA;border-color:#CC5DE8;color:#CC5DE8;transform:translateY(-2px)}
        .email-capture{max-width:520px;margin:28px auto 0;background:#fff;border:2px dashed #FFD93D;border-radius:18px;padding:20px 22px;text-align:center}
        .email-cta{font-weight:700;color:#555;margin-bottom:12px;font-size:.95rem}
        .email-row{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}
        .email-input{flex:1;min-width:200px;padding:12px 16px;border:2px solid #eee;border-radius:30px;font-family:'Nunito',sans-serif;font-size:1rem;font-weight:600}
        .email-input:focus{outline:none;border-color:#FF922B}
        .email-btn{padding:12px 22px;border-radius:30px;border:none;background:linear-gradient(135deg,#FF6B6B,#FF922B);color:#fff;font-weight:800;font-size:.95rem;cursor:pointer;font-family:'Nunito',sans-serif;display:inline-flex;align-items:center;gap:6px;white-space:nowrap}
        .email-btn:hover{transform:translateY(-2px)}
        .email-btn:disabled{opacity:.6;cursor:default;transform:none}
        .email-sent{font-weight:800;color:#1D9E75;font-size:1rem}
        .email-err{color:#E03131;font-weight:700;font-size:.85rem;margin-top:8px}
        .rating-box{max-width:520px;margin:16px auto 0;text-align:center}
        .rating-q{font-weight:700;color:#555;margin-bottom:6px;font-size:.95rem}
        .stars{display:flex;gap:6px;justify-content:center}
        .star{background:none;border:none;cursor:pointer;font-size:2rem;line-height:1;color:#ddd;transition:color .12s,transform .12s;padding:0}
        .star:hover{transform:scale(1.15)}
        .star.on{color:#FFD93D}
        .rating-comment{margin-top:12px;display:flex;flex-direction:column;gap:8px;align-items:center}
        .rating-got{font-weight:700;color:#1D9E75;font-size:.85rem}
        .rating-input{width:100%;max-width:420px;padding:10px 14px;border:2px solid #eee;border-radius:14px;font-family:'Nunito',sans-serif;font-size:.95rem;font-weight:600;resize:vertical}
        .rating-input:focus{outline:none;border-color:#CC5DE8}
        .rating-send{padding:9px 20px;border-radius:30px;border:none;background:#CC5DE8;color:#fff;font-weight:800;font-size:.88rem;cursor:pointer;font-family:'Nunito',sans-serif}
        .rating-send:hover{transform:translateY(-2px)}
        .rating-thanks{font-weight:800;color:#1D9E75;font-size:1rem}
        .icard.swapping{opacity:.6;transform:scale(0.98)}
        @keyframes itemPop{0%{opacity:0;transform:scale(0.94)}60%{transform:scale(1.02)}100%{opacity:1;transform:scale(1)}}
        .icard.just-swapped{animation:itemPop .5s ease-out}
        .addons-block{margin-top:8px;padding:12px 16px 14px;background:linear-gradient(135deg,#FFF8F0 0%,#F3E0FF 100%);border-radius:0 0 18px 18px;border:2.5px solid #E1BEE7;border-top:none;margin-left:14px;margin-right:14px;position:relative;top:-8px}
        .addons-label{display:flex;align-items:center;gap:6px;font-family:'Fredoka One',cursive;font-size:.78rem;color:#7B2FA8;letter-spacing:.3px;margin-bottom:8px;text-transform:uppercase}
        .addons-grid{display:flex;flex-wrap:wrap;gap:8px}
        .addon-chip{display:inline-flex;align-items:center;gap:7px;padding:7px 12px;border-radius:30px;background:#fff;border:2px solid #E1BEE7;color:#7B2FA8;font-weight:800;font-size:.78rem;text-decoration:none;transition:all .15s;cursor:pointer}
        .addon-chip:hover{background:#F3E0FF;border-color:#CC5DE8;transform:translateY(-1px);box-shadow:0 3px 10px rgba(204,93,232,0.25)}
        .addon-arrow{font-size:.9rem;opacity:.6}
        .footer{text-align:center;padding:2rem 1rem;color:#999;font-size:.78rem;font-weight:600;line-height:1.6;max-width:600px;margin:0 auto}
        .footer-links{display:flex;flex-wrap:wrap;gap:8px 16px;justify-content:center;margin-top:14px}
        .footer-link{background:none;border:none;cursor:pointer;font-family:inherit;font-size:.78rem;font-weight:700;color:#7B2FA8;text-decoration:underline;text-decoration-style:dotted;padding:0}
        .footer-link:hover{color:#CC5DE8}
        .footer-divider{color:#ddd}
        .disclosure-banner{background:#FFF8E1;border:1.5px solid #FFE082;border-radius:12px;padding:10px 14px;margin:0 0 1rem;font-size:.78rem;color:#7A5500;font-weight:600;display:flex;gap:8px;align-items:flex-start}
        .disclosure-banner button{background:none;border:none;color:#7B2FA8;font-weight:800;cursor:pointer;text-decoration:underline;text-decoration-style:dotted;padding:0;font-size:inherit}
        .cookie-banner{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:3px solid #CC5DE8;box-shadow:0 -4px 20px rgba(0,0,0,0.1);padding:1rem 1.2rem;z-index:1000;display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:center;max-width:900px;margin:0 auto;border-radius:16px 16px 0 0}
        .cookie-banner p{flex:1;min-width:240px;font-size:.85rem;font-weight:600;color:#555;margin:0}
        .cookie-banner button{padding:10px 22px;border:none;border-radius:30px;background:linear-gradient(135deg,#6BCB77,#4CAF50);color:#fff;font-family:'Fredoka One',cursive;font-size:.9rem;cursor:pointer;box-shadow:0 3px 12px rgba(107,203,119,0.4);transition:transform .15s}
        .cookie-banner button:hover{transform:translateY(-2px)}
        .cookie-banner a{color:#7B2FA8;font-weight:800;text-decoration:underline;text-decoration-style:dotted;cursor:pointer}
        .modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.5);z-index:10000;display:flex;align-items:center;justify-content:center;padding:1rem;animation:fadeIn .2s ease}
        @keyframes fadeIn{from{opacity:0}to{opacity:1}}
        .modal-box{background:#fff;border-radius:24px;max-width:680px;width:100%;max-height:85vh;overflow-y:auto;box-shadow:0 12px 40px rgba(0,0,0,0.3);padding:2rem}
        .modal-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.2rem;padding-bottom:1rem;border-bottom:2px solid #F0E6FF}
        .modal-title{font-family:'Fredoka One',cursive;font-size:1.5rem;color:#333}
        .modal-close{background:#F0E6FF;border:none;width:36px;height:36px;border-radius:50%;cursor:pointer;font-size:1.2rem;font-weight:800;color:#7B2FA8;transition:background .15s}
        .modal-close:hover{background:#E1BEE7}
        .modal-body{font-size:.92rem;line-height:1.65;color:#444;white-space:pre-wrap;font-weight:500}
        .debug{font-size:.72rem;color:#aaa;text-align:center;font-weight:700;margin-top:6px}
        @media(max-width:600px){.card{padding:1.3rem}.occ-grid{grid-template-columns:1fr 1fr}.bag-grid{grid-template-columns:1fr 1fr}}
      `}</style>

      <Confetti trigger={confetti}/>

      <header style={{textAlign:"center",padding:"3rem 1rem 1rem"}}>
        <div style={{fontSize:"3rem",marginBottom:10}}>🎁</div>
        <h1 className="hero-title">Goodie Bag Generator</h1>
        <p style={{fontSize:"1.1rem",color:"#888",fontWeight:600,marginTop:8}}>
          AI-powered party bag ideas for parents &amp; teachers ✨
        </p>
      </header>

      <main style={{maxWidth:740,margin:"0 auto",padding:"0 1rem 4rem"}}>

        {/* Affiliate disclosure banner — required for FTC compliance */}
        <div className="disclosure-banner">
          <span style={{fontSize:"1.1rem"}}>ℹ️</span>
          <div>
            <strong>As an Amazon Associate this site earns from qualifying purchases.</strong> We earn a small commission when you buy through our Amazon links — at no extra cost to you. AI suggestions are estimates; verify allergens, prices, and ages before purchasing.{" "}
            <button onClick={() => setModalContent("disclosure")}>Learn more</button>
          </div>
        </div>

        {/* Popular-themes quick-pick strip — hidden once a bag is showing */}
        {!result && <PopularThemes onPick={loadPreset} disabled={loading} />}

        <div className="card" style={{marginBottom:"2rem"}}>

          {/* Age */}
          <div style={{marginBottom:"1.4rem"}}>
            <label className="flabel">🎂 Kids Age Range</label>
            <div style={{display:"grid",gridTemplateColumns:"1fr auto 1fr",gap:10,alignItems:"center"}}>
              <input className="finput" type="number" name="ageMin" min="1" max="17" value={form.ageMin} onChange={handleChange} placeholder="Min"/>
              <span style={{fontFamily:"'Fredoka One',cursive",color:"#ccc",textAlign:"center"}}>to</span>
              <input className="finput" type="number" name="ageMax" min="1" max="17" value={form.ageMax} onChange={handleChange} placeholder="Max"/>
            </div>
          </div>

          {/* Occasion */}
          <div style={{marginBottom:"1.4rem"}}>
            <label className="flabel">🎉 Occasion</label>
            <div className="occ-grid">
              {OCCASIONS.map(o=>(
                <button key={o.value} className={`occ-btn ${form.occasion===o.value?"sel":""}`}
                  onClick={()=>setForm(f=>({...f,occasion:o.value}))}>
                  {o.label}
                </button>
              ))}
            </div>
          </div>

          {/* Bag Style */}
          <div style={{marginBottom:"1.4rem"}}>
            <label className="flabel">🎁 Bag Style</label>
            <div className="bag-grid">
              {BAG_STYLES.map(b=>(
                <button key={b.value} className={`bag-btn ${form.bagStyle===b.value?"sel":""}`}
                  onClick={()=>setForm(f=>({...f,bagStyle:b.value}))}>
                  {b.label}
                  <span className="hint">{b.hint}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Count + Budget */}
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:"1.6rem"}}>
            <div>
              <label className="flabel">👧 Number of Bags</label>
              <input className="finput" type="number" name="count" min="1" max="500" value={form.count} onChange={handleChange} placeholder="e.g. 25"/>
              <p style={{fontSize:".78rem",color:"#bbb",marginTop:4,fontWeight:600}}>Total bags needed</p>
            </div>
            <div>
              <label className="flabel">💰 Budget per Bag</label>
              <div style={{position:"relative"}}>
                <span style={{position:"absolute",left:14,top:"50%",transform:"translateY(-50%)",fontWeight:800,color:"#bbb"}}>$</span>
                <input className="finput" type="number" name="budget" min="1" max="100" step="0.5" value={form.budget} onChange={handleChange} style={{paddingLeft:28}}/>
              </div>
              <p style={{fontSize:".72rem",color:"#ccc",marginTop:4,fontWeight:600}}>Rough plan: ${totalEst} for {form.count||0} bags</p>
            </div>
          </div>

          {/* Food + Allergies */}
          <div style={{marginBottom:"1.6rem",padding:"1rem 1.2rem",background:"#F9FAFB",borderRadius:14,border:"2px solid #F0E6FF"}}>
            <label className="toggle" style={{marginBottom:form.includeFood?"1rem":0}}>
              <input type="checkbox" checked={form.includeFood}
                onChange={e=>setForm(f=>({...f,includeFood:e.target.checked,allergies:e.target.checked?f.allergies:[]}))}/>
              <span className="toggle-slider"/>
              <span style={{fontFamily:"'Fredoka One',cursive",fontSize:".95rem",color:"#444"}}>
                🍬 Include candy &amp; food
              </span>
            </label>
            {form.includeFood && (
              <div>
                <p style={{fontSize:".78rem",color:"#888",fontWeight:700,marginBottom:8}}>Dietary filters (optional):</p>
                <div className="all-grid">
                  {ALLERGY_OPTIONS.map(a=>(
                    <button key={a.value} className={`all-chip ${form.allergies.includes(a.value)?"sel":""}`}
                      onClick={()=>toggleAllergy(a.value)}>
                      {a.label}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          <button className="gen-btn" onClick={generate} disabled={loading}>
            {loading ? <><span className="spin"/>Building your goodie bags…</> : "✨ Generate Goodie Bag Ideas"}
          </button>
        </div>

        {error && <div className="err-box">⚠️ {error}</div>}

        {result && (
          <div ref={resultsRef}>

            <div style={{textAlign:"center",marginBottom:"2rem"}}>
              <div style={{fontSize:"2.4rem",marginBottom:6}}>🎊</div>
              <h2 style={{fontFamily:"'Fredoka One',cursive",fontSize:"2rem",color:"#333"}}>{result.theme}</h2>
              <p style={{color:"#999",fontWeight:600,marginTop:4}}>{result.tagline}</p>
              <div style={{maxWidth:380,margin:"1.2rem auto 0"}}>
                {(() => {
                  const items = result.items || [];
                  const enrichedItems = items.filter(it => it.packPrice != null);
                  const cartTotal = enrichedItems.reduce((s, it) => s + Number(it.packPrice || 0), 0);
                  const stillResolving = enrichingKeys.size > 0;
                  const allEnriched = enrichedItems.length === items.length && items.length > 0;
                  return (
                    <>
                      <div style={{textAlign:"center"}}>
                        <p style={{fontSize:".78rem",fontWeight:700,color:"#888",letterSpacing:".3px",textTransform:"uppercase"}}>
                          Everything here on Amazon
                        </p>
                        <p style={{fontFamily:"'Fredoka One',cursive",fontSize:"1.8rem",color:"#FF9900",marginTop:2}}>
                          {enrichedItems.length === 0
                            ? <span style={{fontSize:"1rem",color:"#bbb"}}>calculating…</span>
                            : <>≈ ${cartTotal.toFixed(2)}{!allEnriched && <span style={{fontSize:".7rem",color:"#bbb",fontWeight:700,marginLeft:6}}>so far</span>}</>
                          }
                        </p>
                        <p style={{fontSize:".72rem",color:"#bbb",fontWeight:600,marginTop:2,fontStyle:"italic"}}>
                          Real Amazon pack prices for items found{stillResolving && enrichedItems.length > 0 ? " · loading more…" : ""}
                        </p>
                      </div>
                    </>
                  );
                })()}
                {debugInfo && (
                  <p className="debug">
                    {debugInfo.cached
                      ? "⚡ Loaded from cache (saved an API call)"
                      : <>Generated in {debugInfo.attempts} attempt{debugInfo.attempts>1?"s":""}
                          {debugInfo.validationErrors?.length>0 && ` · ${debugInfo.validationErrors.length} validation issue(s)`}</>
                    }
                  </p>
                )}
              </div>
            </div>

            <div style={{display:"grid",gap:14,marginBottom:"1.8rem"}}>
              {(result.items||[]).map((item,i)=>{
                const meta = CAT_META[item.category]||CAT_META.other;
                const isSpecial = item.category==="hero" || item.category==="bag";
                const isSwapping = swappingIndex === i;
                const justSwapped = justSwappedIndex === i;
                const isEnriching = enrichingKeys.has(i) && !item.imageUrl;
                const baseClass = item.category==="hero" ? "icard hero-card"
                                : item.category==="bag"  ? "icard bag-card"
                                : "icard";
                const stateClass = isSwapping ? " swapping" : justSwapped ? " just-swapped" : "";
                return (
                  <div key={`${i}-${item.name}`}>
                    <div className={baseClass + stateClass} style={{borderColor:meta.color+ (isSpecial?"88":"44")}}>
                      <div style={{display:"flex",gap:14,alignItems:"flex-start"}}>
                        {item.imageUrl ? (
                          <img src={item.imageUrl} alt="" loading="lazy"
                            style={{width:64,height:64,objectFit:"contain",borderRadius:12,flexShrink:0,background:"#fff"}} />
                        ) : (
                          <div style={{width:64,flexShrink:0,textAlign:"center"}}>
                            <div style={{fontSize:"2.2rem",lineHeight:1}}>{item.emoji}</div>
                            {isEnriching && (
                              <div className="finding-product">finding product…</div>
                            )}
                          </div>
                        )}
                        <div style={{flex:1,minWidth:0}}>
                          <div style={{display:"flex",alignItems:"center",flexWrap:"wrap",gap:8,marginBottom:5}}>
                            <span className="cbadge" style={{background:meta.color}}>{meta.label}</span>
                            {item.quantity>1 && <span style={{fontSize:".78rem",color:"#bbb",fontWeight:700}}>×{item.quantity} per bag</span>}
                            <span style={{marginLeft:"auto",textAlign:"right"}}>
                              {item.packPrice != null ? (
                                <span style={{fontFamily:"'Fredoka One',cursive",fontSize:"1.05rem",color:"#FF9900"}}>
                                  ${Number(item.packPrice).toFixed(2)}
                                </span>
                              ) : isEnriching ? (
                                <span style={{fontSize:".75rem",color:"#bbb",fontWeight:700,fontStyle:"italic"}}>
                                  price loading…
                                </span>
                              ) : (
                                <span style={{fontSize:".75rem",color:"#bbb",fontWeight:700}}>
                                  ≈ {itemPriceLabel(item)} <span style={{opacity:.8}}>per-bag share (est)</span>
                                </span>
                              )}
                            </span>
                          </div>
                          <h3 style={{fontFamily:"'Fredoka One',cursive",fontSize:"1.05rem",color:"#333",marginBottom:3}}>{item.name}</h3>
                          <p style={{fontSize:".86rem",color:"#777",lineHeight:1.45,fontWeight:600}}>{item.description}</p>
                          <div className="item-actions">
                            <a className="amz-btn" href={item.detailPageURL || amazonLink(item.searchQuery)} target="_blank" rel="noopener noreferrer"
                              onClick={() => track("amazon_click", { enriched: !!item.detailPageURL, category: item.category, item_name: item.name, bag_source: bagSourceRef.current })}>
                              🛒 Shop this item
                            </a>
                            <button className="swap-btn" onClick={() => replaceItem(i)}
                              disabled={swappingIndex !== null}>
                              {isSwapping ? <><span className="swap-spin"/>Replacing…</> : "🔄 Replace item"}
                            </button>
                            <a className="more-btn" href={amazonLink(item.searchQuery)} target="_blank" rel="noopener noreferrer"
                              onClick={() => track("amazon_click", { enriched: false, category: item.category, item_name: item.name, bag_source: bagSourceRef.current })}>
                              🔍 See more options
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Render packaging add-ons right after the bag card */}
                    {item.category === "bag" && (
                      <div className="addons-block">
                        <div className="addons-label">
                          <span style={{fontSize:"1rem"}}>✨</span>
                          <span>Complete your bag</span>
                        </div>
                        <div className="addons-grid">
                          {PACKAGING_ADDONS.map((addon, ai) => {
                            const styleQuery = addon.searchByStyle[form.bagStyle] || addon.searchByStyle.theme;
                            // For themed bags, prepend the occasion theme to the query
                            const occLabel = OCCASIONS.find(o=>o.value===form.occasion)?.label.replace(/[^\w\s]/g,"").trim() || "";
                            const finalQuery = form.bagStyle === "theme" && occLabel
                              ? `${occLabel} ${styleQuery}`.trim()
                              : styleQuery;
                            return (
                              <a key={ai} className="addon-chip"
                                href={amazonLink(finalQuery)} target="_blank" rel="noopener noreferrer">
                                <span style={{fontSize:"1.3rem"}}>{addon.emoji}</span>
                                <span>{addon.name}</span>
                                <span className="addon-arrow">→</span>
                              </a>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Email-my-results — directly below the last bag item, above the tips */}
            <div className="email-capture">
              {emailStatus === "sent" ? (
                <p className="email-sent">📬 Sent! Check your inbox for your goodie bag — we saved it so you can shop anytime.</p>
              ) : (
                <>
                  <p className="email-cta">📧 Want this bag emailed to you? We'll send a link so you can come back and shop anytime.</p>
                  <div className="email-row">
                    <input type="email" value={email} placeholder="you@email.com"
                      onChange={e => { setEmail(e.target.value); if (emailStatus) setEmailStatus(null); }}
                      onKeyDown={e => e.key === "Enter" && submitEmail()}
                      className="email-input" />
                    <button className="email-btn" onClick={submitEmail} disabled={emailStatus==="sending"}>
                      {emailStatus==="sending" ? <><span className="swap-spin"/>Sending…</> : "Email it to me"}
                    </button>
                  </div>
                  {emailStatus === "error" && <p className="email-err">Hmm, that didn't go through. Check the address and try again.</p>}
                </>
              )}
            </div>

            {/* Rating widget */}
            <div className="rating-box">
              {ratingStatus === "sent" ? (
                <p className="rating-thanks">🙏 Thanks for the feedback!</p>
              ) : (
                <>
                  <p className="rating-q">How would you rate this goodie bag?</p>
                  <div className="stars">
                    {[1,2,3,4,5].map(n => (
                      <button key={n} className={"star" + (n <= rating ? " on" : "")}
                        onClick={() => pickStar(n)}
                        aria-label={`${n} star${n>1?"s":""}`}>★</button>
                    ))}
                  </div>
                  {rating > 0 && (
                    <div className="rating-comment">
                      <p className="rating-got">Got it — thanks! Want to add a note?</p>
                      <textarea value={ratingComment} placeholder="Anything you'd change? (optional)"
                        onChange={e => setRatingComment(e.target.value)} rows={2} className="rating-input" />
                      <button className="rating-send" onClick={sendComment}>
                        Send feedback
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>

            <div style={{display:"grid",gap:12,marginBottom:"1.8rem"}}>
              {[
                {icon:"📦",label:"Packaging Tip",text:result.packagingTip,bg:"#FFF8E1",border:"#FFE082"},
                {icon:"🍎",label:"Teacher Tip",   text:result.teacherTip,  bg:"#E8F5E9",border:"#A5D6A7"},
                {icon:"🎮",label:"Fun Activity",  text:result.funActivity, bg:"#EDE7F6",border:"#CE93D8"},
              ].map(t=>(
                <div key={t.label} className="tip-box" style={{background:t.bg,border:`2px solid ${t.border}`}}>
                  <span style={{fontSize:"1.4rem"}}>{t.icon}</span>
                  <div>
                    <span style={{fontFamily:"'Fredoka One',cursive",fontSize:".9rem",color:"#555"}}>{t.label}: </span>
                    <span style={{color:"#444"}}><LinkedTipText text={t.text}/></span>
                  </div>
                </div>
              ))}
            </div>

            <div style={{textAlign:"center"}}>
              <button className="gen-btn" onClick={regenerate} disabled={loading}
                style={{maxWidth:300,background:"linear-gradient(135deg,#CC5DE8,#4D96FF)",boxShadow:"0 6px 20px rgba(204,93,232,0.35)"}}>
                {loading?<><span className="spin"/>Regenerating…</>:"🔄 Regenerate Ideas"}
              </button>
            </div>

          </div>
        )}

        <div className="footer">
          <p>As an Amazon Associate this site earns from qualifying purchases. This site contains Amazon affiliate links; we may earn a commission at no extra cost to you.</p>
          <p style={{marginTop:6}}>Suggestions are AI-generated. Always verify age-appropriateness and allergens for your specific group.</p>
          <div className="footer-links">
            <a className="footer-link" href="https://goodiebaggenerator.com" target="_top" rel="noopener">🏠 Home</a>
            <span className="footer-divider">·</span>
            <button className="footer-link" onClick={() => setModalContent("disclosure")}>Affiliate Disclosure</button>
            <span className="footer-divider">·</span>
            <button className="footer-link" onClick={() => setModalContent("privacy")}>Privacy Policy</button>
            <span className="footer-divider">·</span>
            <button className="footer-link" onClick={() => setModalContent("terms")}>Terms of Service</button>
          </div>
          <p style={{marginTop:14,fontSize:".72rem",color:"#bbb"}}>
            © {new Date().getFullYear()} Goodie Bag Generator. Not affiliated with Amazon.com, Inc.
          </p>
        </div>
      </main>

      {/* Legal modal */}
      {modalContent && LEGAL_CONTENT[modalContent] && (
        <div className="modal-overlay" onClick={() => setModalContent(null)}>
          <div className="modal-box" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <span className="modal-title">{LEGAL_CONTENT[modalContent].title}</span>
              <button className="modal-close" onClick={() => setModalContent(null)} aria-label="Close">✕</button>
            </div>
            <div className="modal-body">{LEGAL_CONTENT[modalContent].body}</div>
          </div>
        </div>
      )}

      {/* Cookie consent banner */}
      {!cookieConsent && (
        <div className="cookie-banner">
          <p>
            🍪 We use minimal browser storage to remember your cookie preference. We don't track you across sites. Amazon may set its own cookies when you click affiliate links.{" "}
            <a onClick={() => setModalContent("privacy")}>See details</a>
          </p>
          <button onClick={acceptCookies}>Got it ✓</button>
        </div>
      )}
    </div>
  );
}
